### ISSUE TITLE
Use attribute to select constructor

### ISSUE THREAD

**Issue by kofifus** [ababik/Remute#10]
It will be useful if in the case of multiple constructors, instead of using `ActivationConfiguration().Configure` to select the constructor you could simply decorate the constructor you want Remute to choose with an attribute ie `[RemuteConstructor]`

Thanks!

**Comment by ababik** [comment]
I like this idea. The reason I've decided to go with imperative approach first is that it's more flexible and satisfy more cases. I'll be able to implement attribute-based configuration later depending on demand.

**Comment by kofifus** [comment]
Great .. to be honest I actually preferring mandating the constructor you need exists as that is good for immutable types .. I find it strange someone will need to change it

**Comment by Lonli-Lokli** [comment]
@ababik did you have a chance to look into Attribute choice?

**Comment by ababik** [comment]
Not yet. Please feel free to reopen this issue to make it a priority.

**Comment by Lonli-Lokli** [comment]
Actually I would like to discuss it first.
With current approach you can change behavior even for external classes which you don't own. 
RemuteCtorAttribute will give more flexibility for simple creations but will lead to modification of classes.
Another approach (which I choose right now) is to use some static methods, internal to component or located in some kind of helper with signature like static Cmp CreateFromRequest(string onlyOneProp) => new Cmp(onlyOneProp, secondProp...)

What do you think? From Dev point of view Attr is less code but less visible, while Static more code and more visible.

**Comment by kofifus** [comment]
Hi all, as far as I can see projects like remute and https://github.com/kofifus/With are obsolete now that C# 9.0 introduced records
