### ISSUE TITLE
Pass a ValueTuple to With

### ISSUE THREAD

**Issue by kofifus** [ababik/Remute#11]
I suggest changing the signature of `Remute.With` from

```
public TInstance With<TInstance, TValue>(TInstance source, Expression<Func<TInstance, TValue>> expression, TValue value)
```

to 

```
public TInstance With<TInstance, TValue>(TInstance source, Expression<Func<TInstance, ValueTuple<TValue,TValue>>> expression)
```

So that instead of:

```
remute.With(expected, x => x.FirstName, "Foo");
```

It will be:

```
remute.With(expected, x => (x.FirstName, "Foo"));
```

The advantage here is that the value can depend on the instance, that is you can now do:

```
remute.With(expected, x => (x.FirstName, "Foo "+x.LastName));
```
 
This can also be just an additional overload of `With` though I feel replacing it is better ...
Any thoughts ?

**Comment by ababik** [comment]
Currently you can "capture" instance like this:
```cs
remute.With(expected, x => x.FirstName, "Foo " + expected.LastName);
```
How `ValueTuple` is better than that?

**Comment by ababik** [comment]
No problem. Thanks for your inquiry.
So currently you can do like this:
```cs
var actual = employee.Remute(x => x.FirstName, "Foo" + employee.LastName);
```
I guess my question is still the same: how ValueTuple is better than that?

**Comment by kofifus** [comment]
got it ! thx
