### ISSUE TITLE
InstanceExpressionCacheKey not needed 

### ISSUE THREAD

**Issue by kofifus** [ababik/Remute#13]
I think the `InstanceExpressionCacheKey` class is not really needed

in 
https://github.com/ababik/Remute/blob/master/Remute/Remute.cs#L288

you can instead simply do:
`var key = processContext.InstanceExpression.ToString();`

**Comment by ababik** [comment]
This is very good point. I did research that and here is what I found  https://stackoverflow.com/questions/9746896/converting-a-lambda-expression-into-a-unique-key-for-caching
So I don't want to use `ToString` to generate key but writing `ExpressionVisitor` looks like an overkill also. So I decided to abstract key as a class and its implementation can be changed in the future but current one is working just fine for me.

Thank you for checking it out. How's you experience with `Remute` so far? What are you using it for?

**Comment by kofifus** [comment]
Interesting .. isn't your class basically equivalent to
'var key = typeof(TSource).ToString()+processContext.InstanceExpression.ToString();' ?

not sure ...

Also I'm not sure the links you posted are relevant because isn't expression here fully constructed when you call tostring ? That question seems to refer to a problem with partial evaluation (linq)..

I am just playing with the code at the moment, impressed ! I didn't think that would be possible ..

**Comment by ababik** [comment]
Here is an example.
You use 2 expressions in the code in the different places:
1) `employee.Remute(x => x.FirstName, ...)`
2) `employee.Remute(emp => emp.FirstName, ...)`
Note 2 different variable names are used `x` and `emp`. `ToString` representation is different.
But from caching point of view it's the same.
To avoid that I lightly parse expression and use `type` instead of instance variable name.

**Comment by kofifus** [comment]
I see thanks!

How will you deal with different namespaces, if multiple namespace have a class with the same name wouldn't your cache keys clash ?

**Comment by ababik** [comment]
I prefer to encapsulate key as a special class and avoid string manipulations.

**Comment by kofifus** [comment]
Hi sorry for late answer ..

I am still confused about this one, why do you need to have the lambda in the key at all ? you are just calculating a delegate in the form `delegate object InstanceDelegate<T>(T src);` so wouldn't just using `T` type as the key be enough ?

Thanks!

**Comment by kofifus** [comment]
sorry for the late reply ..

I am still confused about this - `ResolveInstance` uses `TSource`, `instanceConvertExpression` and `processContext.SourceParameterExpression` to compute `compiledExpression` (https://github.com/ababik/Remute/blob/master/Remute/Remute.cs#L299)

However `processContext.SourceParameterExpression` is not part of the cache key - shouldn't it be there ? and if not, why do we need `processContext.SourceParameterExpression` at all there, can't we use a new ParameterExpression ?

Thanks!

**Comment by ababik** [comment]
Thanks for the comment. Just to make sure I understand your question correctly: how would you write that method `ResolveInstance`?
```
var instanceConvertExpression = Expression.Convert(processContext.InstanceExpression, typeof(object));
var lambdaExpression = Expression.Lambda<ResolveInstanceDelegate<TSource>>(instanceConvertExpression, processContext.SourceParameterExpression);
```
