### ISSUE TITLE
'Remute' is a namespace but is used like a type

### ISSUE THREAD

**Issue by ProductiveRage** [ababik/Remute#4]
If I have the line

`var remute = new Remute();`

then I get an error:

> 'Remute' is a namespace but is used like a type

I added a line "using Remute;" to the top of the file but VS 2017 removed it as unused.

**Comment by ababik** [comment]
@ProductiveRage that' because Remute class is in Remute namespace.
so you do like
```cs
var remute = new Remute.Remute();
```
That's actually confusing. I'll consider to use different namespace.

**Comment by ababik** [comment]
@ProductiveRage I changed namespace to be `Remutable`
So you can do just
```cs
using Remutable;
...
var remute = new Remute();
```

**Comment by ababik** [comment]
@michael-wolfenden that can affect you when update to the latest
