### ISSUE TITLE
Consider a Remute.Instance static property?

### ISSUE THREAD

**Issue by ProductiveRage** [ababik/Remute#5]
If I don't need any custom configuration then maybe I shouldn't need to do "new Remute();" every time, perhaps there should be a static default config property on Remute so that I can do something like this:

`var actual = Remute.Default.With(expected, x => x.FirstName, "Foo");`

Just an idea! (Because I was wondering "why do I need to create new instances of Remute if I'm not doing anything interesting or custom with them).

**Comment by ababik** [comment]
@ProductiveRage that's actually a good idea. I'll simplify API by implementing Default instance.

**Comment by ababik** [comment]
@ProductiveRage now you can do that.
