### ISSUE TITLE
Suggestion: Verbose error messages

### ISSUE THREAD

**Issue by SuddenGunter** [ababik/Remute#9]
![image](https://user-images.githubusercontent.com/15653599/46361961-a6fff400-c677-11e8-8d77-25c565b68958.png)
Here I've got this method's calls.
End here is exception message I've got:
![image](https://user-images.githubusercontent.com/15653599/46362027-ddd60a00-c677-11e8-8390-295bb94a817f.png)
It would be cool, if we can see PropertyName in this, so it would take less time to debug and fix

**Comment by ababik-frozenmountain** [comment]
@SuddenGunter Thanks for the suggestion. I'll extent message to include property name.

**Comment by ababik** [comment]
@SuddenGunter  Thanks for the suggestion. I'll extent message to include property name.

**Comment by SuddenGunter** [comment]
@ababik while you're online - does remute works with optional arguments?

**Comment by SuddenGunter** [comment]
it works, my bad (removed second constructor, but it was in another branch :D)

**Comment by ababik** [comment]
This exception is thrown when type has more than one constructor. Is your `Card` has multiple constructors?
In this case by default Remute doesn't know which one to use. This can be solved using `ActivationConfiguration`.
```
var config = new ActivationConfiguration()
    .Configure<Card>(x => new Card(x.IsFrozen, x.FrozenUnfrozenAt, ...));
var remute = new Remute(config);
var updatedRecord = card
    .Remute(x => x.IsFrozen, resultIsFrozen, remute)
    .Remute(x => x.FrozenUnfrozenAt, DateTime.UtcNow, remute);
```
Using method `Configure` you specify explicitly which constructor to use constructing object of `Card`.
